export interface Book {
    title: string;
    author: string;
    category: string;
    rating: number;
    status: "Completed" | "Reading" | "Wishlist";
    desc: string;
    quote: string;
    img: string;
}

export const BOOKS_CATEGORIES = [
    "All",
    "Non-Fiction",
    "Fiction",
    "Science Fiction",
    "Wattpad",
];

export const BOOKS_DATA: Book[] = [
    {
        title: "The Holy Quran",
        author: "Divine Revelation",
        category: "Non-Fiction",
        rating: 5,
        status: "Reading",
        desc: "The central religious text of Islam. I read it weekly for reflection and guidance.",
        quote: "So verily, with the hardship, there is relief.",
        img: "assets/images/books/quran.jpg",
    },
    {
        title: "Ami Topu",
        author: "Muhammed Zafar Iqbal",
        category: "Fiction",
        rating: 5,
        status: "Completed",
        desc: "The very first book I read, that made me start to read books. A classic heart-touching story about a young boy named Topu.",
        quote: "Childhood memories and the innocence of early friendships shape who we become.",
        img: "assets/images/books/amitopu.jpg",
    },
    {
        title: "Can't Hurt Me",
        author: "David Goggins",
        category: "Non-Fiction",
        rating: 5,
        status: "Completed",
        desc: "The first non-fiction book I read that helped me become mentally strong and defy the odds.",
        quote: "You are in danger of living a life so comfortable and soft, that you will die without ever realizing your true potential.",
        img: "assets/images/books/goggins.jpg",
    },
    {
        title: "Meditations",
        author: "Marcus Aurelius (or generic)",
        category: "Non-Fiction",
        rating: 5,
        status: "Completed",
        desc: "My all-time favorite which I still follow. Reflections on stoicism, peace of mind, and inner strength.",
        quote: "The happiness of your life depends upon the quality of your thoughts.",
        img: "assets/images/books/meditations.jpg",
    },
    {
        title: "The 7 Habits of Highly Effective People",
        author: "Stephen R. Covey",
        category: "Non-Fiction",
        rating: 5,
        status: "Completed",
        desc: "A principle-centered approach for solving personal and professional problems.",
        quote: "Sow a thought, reap an action; sow an action, reap a habit; sow a habit, reap a character; sow a character, reap a destiny.",
        img: "assets/images/books/7habits.jpg",
    },
    {
        title: "Rich Dad Poor Dad",
        author: "Robert Kiyosaki",
        category: "Non-Fiction",
        rating: 4,
        status: "Completed",
        desc: "What the rich teach their kids about money that the poor and middle class do not.",
        quote: "The single most powerful asset we all have is our mind. If it is trained well, it can create enormous wealth.",
        img: "assets/images/books/richdad.jpg",
    },
    {
        title: "How to Win Friends and Influence People",
        author: "Dale Carnegie",
        category: "Non-Fiction",
        rating: 5,
        status: "Completed",
        desc: "Timeless advice on human psychology and communication.",
        quote: "You can make more friends in two months by becoming interested in other people than you can in two years by trying to get other people interested in you.",
        img: "assets/images/books/dalecarnegie.jpg",
    },
    {
        title: "The Miracle Morning",
        author: "Hal Elrod",
        category: "Non-Fiction",
        rating: 4,
        status: "Completed",
        desc: "The not-so-obvious secret guaranteed to transform your life (before 8AM).",
        quote: "Your level of success will rarely exceed your level of personal development.",
        img: "assets/images/books/miraclemorning.jpg",
    },
    {
        title: "Awaken the Giant Within",
        author: "Tony Robbins",
        category: "Non-Fiction",
        rating: 4,
        status: "Completed",
        desc: "How to take immediate control of your mental, emotional, physical and financial destiny.",
        quote: "It is your decisions, and not your conditions, that determine your destiny.",
        img: "assets/images/books/awaken.jpg",
    },
    {
        title: "Ikigai",
        author: "Héctor García & Francesc Miralles",
        category: "Non-Fiction",
        rating: 5,
        status: "Completed",
        desc: "The Japanese secret to a long and happy life.",
        quote: "Only staying active will make you want to live a hundred years.",
        img: "assets/images/books/ikigai.jpg",
    },
    {
        title: "Amar Bondhu Rashed",
        author: "Muhammed Zafar Iqbal",
        category: "Fiction",
        rating: 5,
        status: "Completed",
        desc: "A poignant story set against the backdrop of the Bangladesh Liberation War.",
        quote: "True friendship stands the ultimate test of time and sacrifice.",
        img: "assets/images/books/rashed.jpg",
    },
    {
        title: "Dipu Number Two",
        author: "Muhammed Zafar Iqbal",
        category: "Fiction",
        rating: 5,
        status: "Completed",
        desc: "An adventurous tale of a teenage boy finding his place in a new town.",
        quote: "Adventure can be found in the most mundane of places if you look closely enough.",
        img: "assets/images/books/dipu2.jpg",
    },
    {
        title: "Tuntuni ar Chotaccu",
        author: "Muhammed Zafar Iqbal",
        category: "Fiction",
        rating: 4,
        status: "Completed",
        desc: "A fun and engaging collection of adventures.",
        quote: "Curiosity is the engine of youth.",
        img: "assets/images/books/tuntuni.jpg",
    },
    {
        title: "Feluda (Series)",
        author: "Satyajit Ray",
        category: "Fiction",
        rating: 5,
        status: "Completed",
        desc: "The iconic detective series featuring Pradosh C. Mitter, offering thrilling mysteries and brilliant deductions.",
        quote: "Maganlal Meghraj is not a man to be trifled with.",
        img: "assets/images/books/feluda.jpg",
    },
    {
        title: "Science Fiction Somogro (1-5)",
        author: "Muhammed Zafar Iqbal",
        category: "Science Fiction",
        rating: 5,
        status: "Completed",
        desc: "A brilliant anthology of Bengali science fiction stories exploring space, time, and humanity.",
        quote: "The universe is far stranger than we can ever imagine.",
        img: "assets/images/books/scifisomogro.jpg",
    },
    {
        title: "Ikarus",
        author: "Muhammed Zafar Iqbal",
        category: "Science Fiction",
        rating: 4,
        status: "Completed",
        desc: "An imaginative sci-fi journey with a unique twist.",
        quote: "Flying too close to the sun is dangerous, but the view is unparalleled.",
        img: "assets/images/books/ikarus.jpg",
    },
    {
        title: "Assorted Wattpad Stories",
        author: "Various Authors",
        category: "Wattpad",
        rating: 4,
        status: "Reading",
        desc: "A mix of creative, community-driven stories from talented independent writers.",
        quote: "Everyone has a story to tell.",
        img: "/assets/images/books/wattpad.jpg",
    },
];
