export const travelChapters = [
    {
        chapter: "Bangladesh",
        year: "My Home Country",
        emoji: "🇧🇩",
        intro: "Where I was born and raised. The place that shaped everything before Italy.",
        color: "border-cyan-500",
        badgeColor: "bg-cyan-500/10 text-cyan-500 border-cyan-500/20",
        places: [
            { name: "Dhaka", img: "https://picsum.photos/seed/dhaka-city/800/600", imgWide: "https://picsum.photos/seed/dhaka-skyline/1200/800", desc: "The capital — chaotic, energetic, and unmistakably alive.", details: "Dhaka is one of the densest cities on Earth. The contrast between its chaos and its warmth is something that stays with you." },
            { name: "Chittagong", img: "https://picsum.photos/seed/chittagong-port/800/600", imgWide: "https://picsum.photos/seed/chittagong-hills/1200/800", desc: "Bangladesh's second city. A port city between hills and sea.", details: "Patenga beach at sunset and the rolling hills of Sitakunda make Chittagong feel completely different from the capital." },
            { name: "Sylhet", img: "https://picsum.photos/seed/sylhet-tea/800/600", imgWide: "https://picsum.photos/seed/sylhet-nature/1200/800", desc: "The land of tea gardens and rolling green hills in the northeast.", details: "Sylhet is defined by its endless tea estates, the Sari River, and a pace of life that feels genuinely unhurried." },
        ],
    },
    {
        chapter: "Sicily, Italy",
        year: "2022 — Present",
        emoji: "🌋",
        intro: "Home base. The island that started everything — volcanic, historic, and endlessly surprising.",
        color: "border-emerald-500",
        badgeColor: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20",
        places: [
            { name: "Messina", img: "https://picsum.photos/seed/messina-italy/800/600", imgWide: "https://picsum.photos/seed/messina-harbor/1200/800", desc: "My home city. Famous for its giant astronomical clock and the Strait of Messina.", details: "The 12th-century cathedral and daily clock performance are unmissable. The city's waterfront at sunset is something else entirely." },
            { name: "Taormina", img: "https://picsum.photos/seed/taormina-view/800/600", imgWide: "https://picsum.photos/seed/taormina-theater/1200/800", desc: "Clifftop perfection. Ancient Greek theater overlooking Etna and the Ionian Sea.", details: "Wandering the narrow Via Teatro Greco at dusk, with Etna glowing in the background, is one of those moments you just stop trying to photograph." },
            { name: "Palermo", img: "https://picsum.photos/seed/palermo-streets/800/600", imgWide: "https://picsum.photos/seed/palermo-cathedral/1200/800", desc: "Sicily's capital — chaotic, loud, beautiful, and full of street food.", details: "The Ballarò market at 8am is pure sensory overload. The Norman Palace's Palatine Chapel is one of the most beautiful rooms I've ever entered." },
            { name: "Mount Etna", img: "https://picsum.photos/seed/etna-volcano/800/600", imgWide: "https://picsum.photos/seed/etna-crater/1200/800", desc: "Europe's highest and most active volcano. Hiking on lava feels surreal.", details: "The Silvestri Craters at 1900m look like the surface of another planet. Black ash, sulfur vents, and complete silence." },
            { name: "Milo", img: "https://picsum.photos/seed/milo-sicily/800/600", imgWide: "https://picsum.photos/seed/milo-vineyard/1200/800", desc: "A tiny village on the slopes of Etna, known for its wine and sweeping sea views.", details: "Milo is the kind of place you stumble upon and never want to leave. The Etna DOC wines here are genuinely exceptional." },
            { name: "Catania", img: "https://picsum.photos/seed/catania-city/800/600", imgWide: "https://picsum.photos/seed/catania-square/1200/800", desc: "A gritty, energetic city rebuilt entirely from volcanic lava stone after the 1693 earthquake.", details: "The fish market by the port is unlike anything else. La Pescheria at dawn is equal parts beautiful and overwhelming." },
            { name: "Syracuse", img: "https://picsum.photos/seed/siracusa-ortigia/800/600", imgWide: "https://picsum.photos/seed/siracusa-ancient/1200/800", desc: "One of the greatest cities of antiquity. The Greek Theatre still hosts performances today.", details: "Walking through the Archaeological Park of Neapolis connects you to 2,500 years of history. Ortigia island at night is magical." },
        ],
    },
    {
        chapter: "Mainland Italy",
        year: "2023 — Present",
        emoji: "🇮🇹",
        intro: "Venturing beyond Sicily — from the deep south all the way to the industrial north.",
        color: "border-blue-500",
        badgeColor: "bg-blue-500/10 text-blue-500 border-blue-500/20",
        places: [
            { name: "Calabria", img: "https://picsum.photos/seed/calabria-coast/800/600", imgWide: "https://picsum.photos/seed/calabria-mountains/1200/800", desc: "Just across the Strait of Messina — rugged, wild, and underrated.", details: "The Aspromonte national park and the crystal-clear Ionian coast make Calabria one of Italy's best-kept secrets." },
            { name: "Siena", img: "https://picsum.photos/seed/siena-tuscany/800/600", imgWide: "https://picsum.photos/seed/siena-piazza/1200/800", desc: "Medieval Tuscany at its finest. The Piazza del Campo is one of the greatest public squares in the world.", details: "Siena is one of the few Italian cities where cars feel completely out of place. The Duomo's striped marble is stunning up close." },
            { name: "Bologna", img: "https://picsum.photos/seed/bologna-food/800/600", imgWide: "https://picsum.photos/seed/bologna-towers/1200/800", desc: "La Grassa (The Fat One). Europe's oldest university city and home to the best food in Italy.", details: "The 40km of porticoes, the Two Towers, and the impossible depth of tagliatelle al ragù — Bologna is a city that rewards slow exploration." },
            { name: "Venice", img: "https://picsum.photos/seed/venice-canal/800/600", imgWide: "https://picsum.photos/seed/venice-gondola/1200/800", desc: "Impossible, impractical, and unforgettable. There's nothing else like it.", details: "Getting deliberately lost in the back canals away from San Marco is the only way to experience Venice honestly." },
            { name: "Milan", img: "https://picsum.photos/seed/milan-duomo/800/600", imgWide: "https://picsum.photos/seed/milan-modern/1200/800", desc: "Italy's capital of design, finance, and fashion. The Duomo alone is worth the trip.", details: "Milan sits at the crossroads of Italian ambition and European modernity. Home to Bicocca — one of the universities on my MSc shortlist." },
            { name: "Turin", img: "https://picsum.photos/seed/turin-alps/800/600", imgWide: "https://picsum.photos/seed/turin-architecture/1200/800", desc: "Elegant, underrated, and home to Politecnico di Torino — one of Europe's top engineering universities.", details: "Turin feels like a city that rewards those who look closely: baroque arcades, great coffee culture, and the Alps visible on clear days. PoliTo is a serious option for my MSc in Data Science." },
        ],
    },
    {
        chapter: "Germany",
        year: "2024",
        emoji: "🇩🇪",
        intro: "First trip outside Italy — a complete change of pace, scale, and culture.",
        color: "border-yellow-500",
        badgeColor: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
        places: [
            { name: "Germany", img: "https://picsum.photos/seed/berlin-wall/800/600", imgWide: "https://picsum.photos/seed/germany-forest/1200/800", desc: "First trip outside Italy. A completely different pace — efficient, orderly, and fascinating.", details: "The contrast with Sicily couldn't be sharper: infrastructure that just works, forests, rivers, and a culture that takes engineering seriously." },
        ],
    },
    {
        chapter: "Saudi Arabia",
        year: "2024",
        emoji: "🇸🇦",
        intro: "First trip outside Europe — a family journey to the Arabian Peninsula.",
        color: "border-orange-500",
        badgeColor: "bg-orange-500/10 text-orange-500 border-orange-500/20",
        places: [
            { name: "Saudi Arabia", img: "https://picsum.photos/seed/mecca/800/600", imgWide: "https://picsum.photos/seed/saudi-desert/1200/800", desc: "First trip outside Europe — a family visit to the Arabian Peninsula.", details: "A journey that connected me back to roots, culture, and a scale of landscape and architecture unlike anything in Europe." },
        ],
    },
];
